### ISSUE TITLE
Sorting Deletes Items in Mob Crusher

### ISSUE THREAD

**Issue by mxnmnm** [eve0415/IFPatcher#3]
I sorted the items in the mob crusher using inventory sorter and it caused them to get deleted. Thankfully inventory sorter has a blacklist in the configs (need to figure out what to put in there for it to work lol) but it would be nice for it to not delete the items inside.

**Comment by mxnmnm** [comment]
Well they had commands so that's nice

**Comment by eve0415** [comment]
Thank you for reporting. I found out that this happens to any machine that has an inventory.
I'll try to find a way to fix this but I don't have enough time just now.

**Comment by eve0415** [comment]
I did some investigation and I think this issue is more like a bug from [inventory sorter](https://github.com/cpw/inventorysorter) itself. Looking at the code and doing some research, this issue is exactly same with [this](https://github.com/cpw/inventorysorter/issues/114).

You can ask the developer of the `inventory sorter` or find alternative, such as [Inventory Tweaks](https://www.curseforge.com/minecraft/mc-mods/inventory-tweaks)
